### ISSUE TITLE
Найс хардкод

### ISSUE THREAD

**Issue by KIBORG04** [Dominig12/TelepadGuru#1]
```
************** Текст исключения **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TelepadGuru.Form1.GetAdress() in C:\Users\Даня\Desktop\hello\TelepadGuru\Form1.cs:line 375
   at TelepadGuru.Form1.button7_Click(Object sender, EventArgs e) in C:\Users\Даня\Desktop\hello\TelepadGuru\Form1.cs:line 475
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```
при клике на кнопку ОТКРЫТЬ рантаймит

**Comment by Dominig12** [comment]
Принято, будем исправлять

**Comment by Dominig12** [comment]
Исправлено с новым релизом
